create table if not exists "user" (
    "id" bigint generated by default as identity not null,
    "auth_id" varchar(255) not null,
    "first_name" varchar(255) not null,
    "middle_names" varchar(255),
    "last_name" varchar(255) not null,
    "email" varchar(255) not null unique,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id")
);
create index idx_user_auth_id on "user" ("auth_id");

create table if not exists employee_department (
    "id" bigint generated by default as identity not null,
    "name" varchar(255) not null unique,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id")
);

create table if not exists employee (
    "id" bigint generated by default as identity not null,
    "auth_id" varchar(255) not null,
    "first_name" varchar(255) not null,
    "middle_names" varchar(255),
    "last_name" varchar(255) not null,
    "department_id" bigint not null,
    "email" varchar(255) not null unique,
    "phone" varchar(20) not null unique,
    "address_first_line" varchar(255) not null,
    "address_second_line" varchar(255),
    "address_city" varchar(255) not null,
    "address_post_code" varchar(15) not null,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id"),
    constraint fk_employee_department
        foreign key ("department_id")
        references employee_department ("id")
        on update cascade
        on delete restrict
);

create table if not exists product (
    "id" bigint generated by default as identity not null,
    "name" varchar(255) not null,
    "price" decimal(9,2) not null,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id")
);

create table if not exists product_inventory (
    "id" bigint generated by default as identity not null,
    "product_id" bigint not null,
    "stock" integer not null,
    "low_stock_threshold" integer not null,
    "low_stock_alerted" boolean not null default false,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id"),
    constraint fk_product_inventory_product
        foreign key ("product_id")
        references product ("id")
        on update cascade
        on delete restrict
);

create table if not exists "order" (
    "id" char(36) not null,
    "user_id" bigint not null,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id"),
    constraint fk_order_user
        foreign key ("user_id")
        references "user" ("id")
        on update cascade
        on delete restrict
);

create table if not exists product_order (
    "id" bigint generated by default as identity not null,
    "product_id" bigint not null,
    "quantity" smallint not null,
    "user_id" bigint not null,
    "order_id" char(36) not null,
    "status" varchar(50) not null,
    "created_at" timestamp,
    "last_modified_at" timestamp,
    "last_modified_by" varchar(255) not null default 'system',
    "deleted" boolean not null default false,
    primary key ("id"),

    constraint fk_product_order_product
        foreign key ("product_id")
        references product ("id")
        on update cascade
        on delete restrict,

    constraint fk_product_order_user
        foreign key ("user_id")
        references "user" ("id")
        on update cascade
        on delete restrict,

    constraint fk_product_order_order
        foreign key ("order_id")
        references "order" ("id")
        on update cascade
        on delete restrict
);

create index idx_product_order_user_id on product_order ("user_id");
create index idx_product_order_order_id on product_order ("order_id");